--- 
title: "LAPORAN PENILAIAN PROGRAM"
subtitle: "PROGRAM PEMERKASAAN DAN TRANSFORMASI MINDA PENERIMA BANTUAN JABATAN KEBAJIKAN MASYARAKAT(PT-MINDA JKM)"
author: "Unit Penyelidikan Penilaian BPKK"
date: " Kemaskini `r Sys.Date()`"
site: bookdown::bookdown_site
---


# MAKLUMAT PROGRAM

| PERKARA          	| MAKLUMAT                                                                                                                                                                         	|
|------------------	|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| TAHUN            	| 2022                                                                                                                                                                             	|
| NAMA             	| PROGRAM   PEMERKASAAN DAN TRANSFORMASI MINDA PENERIMA BANTUAN JABATAN KEBAJIKAN MASYARAKAT (PT-MINDA JKM)                                                                        	|
| OBJEKTIF         	| 1.Meningkatkan pengetahuan dan kemahiran untuk memantapkan institusi keluarga penerima Bantuan JKM yang produktif khususnya penerima Skim Kanak-kanak JKM   (BKK);               	|
|                  	| 2. Memberi kesedaran kepada penerima Bantuan JKM yang produktif tentang tanggungjawab dalam keluarga dan kemiskinan tidak sepatutnya diwarisi;                                   	|
|                  	| 3. Memberi pemahaman dan kesedaran berkaitan kewangan JKM adalah sumber kewangan sementara untuk penerima Bantuan JKM dapat meneruskan kelangsungan dan kesejahteraan hidup; dan 	|
|                  	| 4. Memupuk sikap positif di kalangan penerima Bantuan JKM untuk berjaya dalam hidup.                                                                                             	|
| KAEDAH PENILAIAN 	| LAMPIRAN   2                                                                                              

**PROGRAM 1**

<table style=";">
    <tbody>
        <tr>
            <td style="border:1.0pt solid #A6A6A6;height:18.9pt;padding:0cm 5.4pt;vertical-align:top;width:113.15pt;">
                <strong>Tarikh</strong>
            </td>
            <td style="border-bottom-style:solid;border-color:#A6A6A6;border-left-style:none;border-right-style:solid;border-top-style:solid;border-width:1.0pt;height:18.9pt;padding:0cm 5.4pt;vertical-align:top;width:361.5pt;">
                22 September 2022
            </td>
        </tr>
        <tr>
            <td style="border-bottom-style:solid;border-color:#A6A6A6;border-left-style:solid;border-right-style:solid;border-top-style:none;border-width:1.0pt;height:17.35pt;padding:0cm 5.4pt;vertical-align:top;width:113.15pt;">
                <strong>Tempat</strong>
            </td>
            <td style="border-bottom:1.0pt solid #A6A6A6;border-left-style:none;border-right:1.0pt solid #A6A6A6;border-top-style:none;height:17.35pt;padding:0cm 5.4pt;vertical-align:top;width:361.5pt;">
                MMU CYBERJAYA
            </td>
        </tr>
        <tr>
            <td style="border-bottom-style:solid;border-color:#A6A6A6;border-left-style:solid;border-right-style:solid;border-top-style:none;border-width:1.0pt;height:19.9pt;padding:0cm 5.4pt;vertical-align:top;width:113.15pt;">
                <strong>Bilangan peserta</strong>
            </td>
            <td style="border-bottom:1.0pt solid #A6A6A6;border-left-style:none;border-right:1.0pt solid #A6A6A6;border-top-style:none;height:19.9pt;padding:0cm 5.4pt;vertical-align:top;width:361.5pt;">
                47
            </td>
        </tr>
    </tbody>
</table>

**PROGRAM 2**

<table style=";">
    <tbody>
        <tr>
            <td style="border:1.0pt solid #A6A6A6;height:18.9pt;padding:0cm 5.4pt;width:113.15pt;">
                <strong>Tarikh</strong>
            </td>
            <td style="border-bottom-style:solid;border-color:#A6A6A6;border-left-style:none;border-right-style:solid;border-top-style:solid;border-width:1.0pt;height:18.9pt;padding:0cm 5.4pt;width:361.5pt;">
                2 November 2022
            </td>
        </tr>
        <tr>
            <td style="border-bottom-style:solid;border-color:#A6A6A6;border-left-style:solid;border-right-style:solid;border-top-style:none;border-width:1.0pt;height:17.35pt;padding:0cm 5.4pt;width:113.15pt;">
                <strong>Tempat</strong>
            </td>
            <td style="border-bottom:1.0pt solid #A6A6A6;border-left-style:none;border-right:1.0pt solid #A6A6A6;border-top-style:none;height:17.35pt;padding:0cm 5.4pt;width:361.5pt;">
                INTI INTERNATIONAL UNIVERSITY, NILAI
            </td>
        </tr>
        <tr>
            <td style="border-bottom-style:solid;border-color:#A6A6A6;border-left-style:solid;border-right-style:solid;border-top-style:none;border-width:1.0pt;height:17.95pt;padding:0cm 5.4pt;width:113.15pt;">
                <strong>Bilangan peserta</strong>
            </td>
            <td style="border-bottom:1.0pt solid #A6A6A6;border-left-style:none;border-right:1.0pt solid #A6A6A6;border-top-style:none;height:17.95pt;padding:0cm 5.4pt;width:361.5pt;">
                57
            </td>
        </tr>
    </tbody>
</table>





